root:
    path: /
    controller: Eventum\Controller\IndexController::defaultAction

index:
    path: /index.php
    controller: Eventum\Controller\IndexController::defaultAction

confirm:
    path: /confirm.php
    methods: GET
    controller: Eventum\Controller\ConfirmController::defaultAction

scm_ping:
    path: /scm_ping
    methods: POST
    controller: Eventum\Controller\ScmPingController::defaultAction

searchbar:
    path: /searchbar.php
    methods: GET
    controller: Eventum\Controller\SearchbarController::defaultAction

forgot_password:
    path: /forgot_password.php
    methods: GET|POST
    controller: Eventum\Controller\ForgotPasswordController::defaultAction

login:
    path: /login.php
    controller: Eventum\Controller\SecurityController::login

logout:
    path: /logout.php
    methods: GET
    # NB: controller is not needed

select_project:
    path: /select_project.php
    methods: GET
    controller: Eventum\Controller\SelectProjectController::defaultAction

setup:
    path: /setup
    methods: GET|POST
    controller: Eventum\Controller\Setup\SetupController::defaultAction

front:
    path: /front
    controller: Eventum\Controller\FrontController::indexAction

# vim:ts=4:sw=4:et
